#!/bin/bash
set -e
APP="$1"; PORT="$2"

# default nginx.conf -- I don't have SSL on my domain, so 
# I don't have config for it here. When I enable that later,
# I'll improve that.  PRs welcome.
cat<<EOF > $HOME/$APP/nginx.conf
location /$APP/ {
  proxy_pass  http://127.0.0.1:$PORT;
  proxy_http_version 1.1;
  proxy_set_header Upgrade \$http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_set_header Host \$http_host;
  proxy_set_header X-Forwarded-Proto \$scheme;
  proxy_set_header X-Forwarded-For \$remote_addr;
  proxy_set_header X-Forwarded-Port \$server_port;
  proxy_set_header X-Request-Start \$msec;
}
EOF
pluginhook nginx-pre-reload $APP
nc -U $HOME/reload-nginx
